export type SpendingNature = "essential" | "discretionary" | "mixed" | "neutral" | "high-risk" | "waste" | "debt" | "investment" | "income";

export interface KnowledgeRule {
  id: string;
  patterns: string[];
  category: string;
  nature: SpendingNature;
  warningShare: number;
  opinion: string;
  action: string;
}

export const FINANCIAL_KNOWLEDGE_BASE: KnowledgeRule[] = [
  {
    id: "steam",
    patterns: ["Steam","Valve"],
    category: "Jogos",
    nature: "discretionary",
    warningShare: 0.03,
    opinion: "Jogos estão consumindo uma fatia relevante da renda.",
    action: "Defina um teto mensal para jogos e espere 48 horas antes de comprar.",
  },
  {
    id: "playstation",
    patterns: ["PlayStation","PSN"],
    category: "Jogos",
    nature: "discretionary",
    warningShare: 0.03,
    opinion: "Compras na PlayStation passaram do limite saudável do mês.",
    action: "Use a lista de desejos e compre apenas em promoções planejadas.",
  },
  {
    id: "xbox",
    patterns: ["Xbox","Microsoft Store"],
    category: "Jogos",
    nature: "discretionary",
    warningShare: 0.03,
    opinion: "Gastos com Xbox merecem revisão.",
    action: "Pause compras até o próximo ciclo mensal.",
  },
  {
    id: "nintendo",
    patterns: ["Nintendo","eShop"],
    category: "Jogos",
    nature: "discretionary",
    warningShare: 0.03,
    opinion: "Jogos da Nintendo estão pesando no orçamento.",
    action: "Escolha um jogo por vez e conclua antes de comprar outro.",
  },
  {
    id: "epic",
    patterns: ["Epic Games"],
    category: "Jogos",
    nature: "discretionary",
    warningShare: 0.02,
    opinion: "Compras na Epic estão frequentes.",
    action: "Aproveite jogos gratuitos antes de novas compras.",
  },
  {
    id: "ifood",
    patterns: ["iFood"],
    category: "Delivery",
    nature: "discretionary",
    warningShare: 0.06,
    opinion: "Delivery está levando dinheiro que poderia acelerar suas metas.",
    action: "Planeje refeições e limite delivery a dias específicos.",
  },
  {
    id: "rappi",
    patterns: ["Rappi"],
    category: "Delivery",
    nature: "discretionary",
    warningShare: 0.05,
    opinion: "Pedidos na Rappi estão acima do confortável.",
    action: "Compare o custo com mercado e cozinhe mais vezes.",
  },
  {
    id: "zé delivery",
    patterns: ["Zé Delivery","Ze Delivery"],
    category: "Bebidas",
    nature: "discretionary",
    warningShare: 0.03,
    opinion: "Bebidas por delivery estão drenando renda.",
    action: "Crie um limite semanal e evite pedidos por impulso.",
  },
  {
    id: "uber",
    patterns: ["Uber"],
    category: "Transporte",
    nature: "mixed",
    warningShare: 0.08,
    opinion: "O custo com Uber está alto para sua renda.",
    action: "Compare com transporte público ou agrupe deslocamentos.",
  },
  {
    id: "99",
    patterns: ["99 App","99 Tecnologia"],
    category: "Transporte",
    nature: "mixed",
    warningShare: 0.07,
    opinion: "Corridas por aplicativo estão frequentes.",
    action: "Planeje rotas e estabeleça um teto semanal.",
  },
  {
    id: "netflix",
    patterns: ["Netflix"],
    category: "Streaming",
    nature: "discretionary",
    warningShare: 0.015,
    opinion: "A assinatura da Netflix pesa junto com outros streamings.",
    action: "Mantenha apenas os serviços usados toda semana.",
  },
  {
    id: "spotify",
    patterns: ["Spotify"],
    category: "Streaming",
    nature: "discretionary",
    warningShare: 0.01,
    opinion: "Revise se o Spotify ainda entrega valor.",
    action: "Considere plano família apenas com pessoas elegíveis.",
  },
  {
    id: "disney",
    patterns: ["Disney Plus","Disney+"],
    category: "Streaming",
    nature: "discretionary",
    warningShare: 0.01,
    opinion: "Mais uma assinatura reduz sua sobra mensal.",
    action: "Faça rodízio de streamings em vez de manter todos.",
  },
  {
    id: "max",
    patterns: ["HBO Max","Max.com"],
    category: "Streaming",
    nature: "discretionary",
    warningShare: 0.01,
    opinion: "O streaming Max deve entrar no teto de assinaturas.",
    action: "Cancele durante meses sem séries em uso.",
  },
  {
    id: "prime",
    patterns: ["Amazon Prime"],
    category: "Assinaturas",
    nature: "mixed",
    warningShare: 0.015,
    opinion: "Prime pode incentivar compras além da assinatura.",
    action: "Avalie assinatura e compras geradas por conveniência.",
  },
  {
    id: "globoplay",
    patterns: ["Globoplay"],
    category: "Streaming",
    nature: "discretionary",
    warningShare: 0.01,
    opinion: "Globoplay soma ao custo recorrente de entretenimento.",
    action: "Faça rodízio mensal entre plataformas.",
  },
  {
    id: "youtube",
    patterns: ["YouTube Premium"],
    category: "Streaming",
    nature: "discretionary",
    warningShare: 0.01,
    opinion: "YouTube Premium deve caber no teto de assinaturas.",
    action: "Revise o uso antes da próxima renovação.",
  },
  {
    id: "deezer",
    patterns: ["Deezer"],
    category: "Streaming",
    nature: "discretionary",
    warningShare: 0.01,
    opinion: "Deezer pode estar duplicando outro serviço de música.",
    action: "Mantenha apenas uma plataforma de música.",
  },
  {
    id: "amazon",
    patterns: ["Amazon","Amazon.com.br"],
    category: "Compras",
    nature: "mixed",
    warningShare: 0.08,
    opinion: "Compras na Amazon estão altas.",
    action: "Use lista de 48 horas e remova compras por impulso.",
  },
  {
    id: "mercado livre",
    patterns: ["Mercado Livre","Mercado Pago"],
    category: "Compras",
    nature: "mixed",
    warningShare: 0.08,
    opinion: "Mercado Livre está ocupando muito do orçamento.",
    action: "Separe reposição necessária de desejo.",
  },
  {
    id: "shopee",
    patterns: ["Shopee"],
    category: "Compras",
    nature: "discretionary",
    warningShare: 0.05,
    opinion: "Pequenas compras na Shopee estão se acumulando.",
    action: "Some frete e compras do mês antes de finalizar.",
  },
  {
    id: "shein",
    patterns: ["Shein"],
    category: "Vestuário",
    nature: "discretionary",
    warningShare: 0.04,
    opinion: "Vestuário na Shein passou do teto sugerido.",
    action: "Espere sete dias e revise o que realmente falta.",
  },
  {
    id: "aliexpress",
    patterns: ["AliExpress"],
    category: "Compras",
    nature: "discretionary",
    warningShare: 0.04,
    opinion: "Compras internacionais estão comprometendo a sobra.",
    action: "Considere impostos, prazo e necessidade real.",
  },
  {
    id: "magalu",
    patterns: ["Magazine Luiza","Magalu"],
    category: "Compras",
    nature: "mixed",
    warningShare: 0.08,
    opinion: "Compras no Magalu merecem planejamento.",
    action: "Evite parcelar itens de consumo rápido.",
  },
  {
    id: "casas bahia",
    patterns: ["Casas Bahia"],
    category: "Compras",
    nature: "mixed",
    warningShare: 0.08,
    opinion: "Parcelamentos podem esconder o custo mensal real.",
    action: "Compare preço à vista e impacto das parcelas.",
  },
  {
    id: "fast shop",
    patterns: ["Fast Shop"],
    category: "Eletrônicos",
    nature: "discretionary",
    warningShare: 0.06,
    opinion: "Eletrônicos estão adiando objetivos maiores.",
    action: "Crie um fundo específico antes de comprar.",
  },
  {
    id: "kabum",
    patterns: ["KaBuM","Kabum"],
    category: "Eletrônicos",
    nature: "discretionary",
    warningShare: 0.06,
    opinion: "Hardware está consumindo uma parcela alta da renda.",
    action: "Planeje upgrades por necessidade e vida útil.",
  },
  {
    id: "terabyte",
    patterns: ["Terabyte"],
    category: "Eletrônicos",
    nature: "discretionary",
    warningShare: 0.06,
    opinion: "Gastos com computador estão elevados.",
    action: "Priorize a peça que resolve o gargalo real.",
  },
  {
    id: "pichau",
    patterns: ["Pichau"],
    category: "Eletrônicos",
    nature: "discretionary",
    warningShare: 0.06,
    opinion: "Compras gamer estão competindo com suas metas.",
    action: "Defina orçamento anual para upgrades.",
  },
  {
    id: "apple",
    patterns: ["Apple.com","Apple Store"],
    category: "Eletrônicos",
    nature: "discretionary",
    warningShare: 0.08,
    opinion: "Produtos Apple têm alto impacto no caixa.",
    action: "Calcule custo por ano de uso antes de trocar.",
  },
  {
    id: "google play",
    patterns: ["Google Play"],
    category: "Aplicativos",
    nature: "discretionary",
    warningShare: 0.02,
    opinion: "Compras em aplicativos estão se acumulando.",
    action: "Desative compras com um toque e revise assinaturas.",
  },
  {
    id: "app store",
    patterns: ["App Store","iTunes"],
    category: "Aplicativos",
    nature: "discretionary",
    warningShare: 0.02,
    opinion: "Apps e compras digitais passaram do teto.",
    action: "Cancele testes gratuitos antes da renovação.",
  },
  {
    id: "mercado",
    patterns: ["Atacadão","Assaí","Carrefour","Extra","Pão de Açúcar"],
    category: "Alimentação",
    nature: "essential",
    warningShare: 0.22,
    opinion: "Mercado está acima da referência mensal.",
    action: "Planeje cardápio, lista e compare preço por unidade.",
  },
  {
    id: "atacadao",
    patterns: ["Atacadão"],
    category: "Alimentação",
    nature: "essential",
    warningShare: 0.22,
    opinion: "Compras no atacado precisam gerar economia real.",
    action: "Evite volume de produtos que podem vencer.",
  },
  {
    id: "assai",
    patterns: ["Assaí","Assai"],
    category: "Alimentação",
    nature: "essential",
    warningShare: 0.22,
    opinion: "A conta de mercado está elevada.",
    action: "Compare marcas e reduza desperdício.",
  },
  {
    id: "carrefour",
    patterns: ["Carrefour"],
    category: "Alimentação",
    nature: "essential",
    warningShare: 0.22,
    opinion: "Supermercado passou da faixa planejada.",
    action: "Faça uma lista baseada no cardápio semanal.",
  },
  {
    id: "pao acucar",
    patterns: ["Pão de Açúcar","Pao de Acucar"],
    category: "Alimentação",
    nature: "essential",
    warningShare: 0.2,
    opinion: "O mercado está caro para a renda atual.",
    action: "Compare itens básicos em lojas mais econômicas.",
  },
  {
    id: "mcdonalds",
    patterns: ["McDonald's","McDonalds"],
    category: "Restaurantes",
    nature: "discretionary",
    warningShare: 0.035,
    opinion: "Fast-food está frequente.",
    action: "Defina um limite de refeições fora por semana.",
  },
  {
    id: "burger king",
    patterns: ["Burger King"],
    category: "Restaurantes",
    nature: "discretionary",
    warningShare: 0.035,
    opinion: "Fast-food está reduzindo sua sobra.",
    action: "Leve lanche ou planeje refeições rápidas em casa.",
  },
  {
    id: "outback",
    patterns: ["Outback"],
    category: "Restaurantes",
    nature: "discretionary",
    warningShare: 0.04,
    opinion: "Restaurantes estão pesando nas metas.",
    action: "Reserve esse gasto para ocasiões planejadas.",
  },
  {
    id: "starbucks",
    patterns: ["Starbucks"],
    category: "Cafés",
    nature: "discretionary",
    warningShare: 0.02,
    opinion: "Cafés fora de casa estão somando mais do que parecem.",
    action: "Crie um teto semanal para cafés e lanches.",
  },
  {
    id: "smart fit",
    patterns: ["Smart Fit"],
    category: "Saúde",
    nature: "mixed",
    warningShare: 0.03,
    opinion: "Academia sem uso é desperdício recorrente.",
    action: "Confirme frequência; se baixa, pause ou troque o plano.",
  },
  {
    id: "bluefit",
    patterns: ["Bluefit"],
    category: "Saúde",
    nature: "mixed",
    warningShare: 0.03,
    opinion: "A mensalidade da academia precisa ter uso consistente.",
    action: "Meça o custo por treino no mês.",
  },
  {
    id: "drogasil",
    patterns: ["Drogasil","Droga Raia","Raia"],
    category: "Saúde",
    nature: "essential",
    warningShare: 0.08,
    opinion: "Farmácia está alta; saúde não deve ser cortada sem análise.",
    action: "Procure genéricos com orientação profissional e compare preços.",
  },
  {
    id: "pague menos",
    patterns: ["Pague Menos"],
    category: "Saúde",
    nature: "essential",
    warningShare: 0.08,
    opinion: "Medicamentos estão afetando o orçamento.",
    action: "Pesquise programas de desconto e reembolso.",
  },
  {
    id: "petz",
    patterns: ["Petz"],
    category: "Pets",
    nature: "mixed",
    warningShare: 0.06,
    opinion: "Gastos com pet estão acima do previsto.",
    action: "Separe saúde do pet de acessórios por impulso.",
  },
  {
    id: "cobasi",
    patterns: ["Cobasi"],
    category: "Pets",
    nature: "mixed",
    warningShare: 0.06,
    opinion: "O orçamento do pet merece uma categoria própria.",
    action: "Compre ração por custo por quilo e planeje veterinário.",
  },
  {
    id: "posto",
    patterns: ["Shell","Ipiranga","Petrobras","Posto"],
    category: "Combustível",
    nature: "essential",
    warningShare: 0.12,
    opinion: "Combustível está alto.",
    action: "Agrupe trajetos e acompanhe consumo por quilômetro.",
  },
  {
    id: "sem parar",
    patterns: ["Sem Parar"],
    category: "Transporte",
    nature: "mixed",
    warningShare: 0.04,
    opinion: "Pedágios e estacionamento estão relevantes.",
    action: "Inclua esses custos no custo total do carro.",
  },
  {
    id: "localiza",
    patterns: ["Localiza","Movida","Unidas"],
    category: "Transporte",
    nature: "mixed",
    warningShare: 0.1,
    opinion: "Aluguel de carro teve grande impacto.",
    action: "Compare diária total com transporte por aplicativo.",
  },
  {
    id: "latam",
    patterns: ["LATAM","Gol Linhas","Azul Linhas"],
    category: "Viagens",
    nature: "discretionary",
    warningShare: 0.12,
    opinion: "Viagens estão comprometendo uma fatia alta da renda.",
    action: "Crie um fundo de viagem antes de emitir.",
  },
  {
    id: "booking",
    patterns: ["Booking.com"],
    category: "Viagens",
    nature: "discretionary",
    warningShare: 0.1,
    opinion: "Hospedagem está competindo com outras metas.",
    action: "Compare política de cancelamento e custo total.",
  },
  {
    id: "airbnb",
    patterns: ["Airbnb"],
    category: "Viagens",
    nature: "discretionary",
    warningShare: 0.1,
    opinion: "Hospedagem precisa ser planejada com antecedência.",
    action: "Inclua taxas e alimentação no orçamento da viagem.",
  },
  {
    id: "cinema",
    patterns: ["Cinemark","UCI","Kinoplex"],
    category: "Lazer",
    nature: "discretionary",
    warningShare: 0.025,
    opinion: "Cinema e lanches estão somando bastante.",
    action: "Use promoções e defina um teto de lazer.",
  },
  {
    id: "sympla",
    patterns: ["Sympla"],
    category: "Eventos",
    nature: "discretionary",
    warningShare: 0.03,
    opinion: "Eventos estão acima da faixa de lazer.",
    action: "Escolha os eventos de maior valor pessoal.",
  },
  {
    id: "ingresso",
    patterns: ["Ingresso.com"],
    category: "Lazer",
    nature: "discretionary",
    warningShare: 0.025,
    opinion: "Ingressos frequentes reduzem a verba das metas.",
    action: "Planeje o lazer no começo do mês.",
  },
  {
    id: "nubank",
    patterns: ["Nubank"],
    category: "Cartão",
    nature: "neutral",
    warningShare: 0.35,
    opinion: "A fatura do cartão está muito alta em relação à renda.",
    action: "Abra a composição da fatura; cartão é meio de pagamento, não categoria.",
  },
  {
    id: "inter",
    patterns: ["Banco Inter"],
    category: "Cartão",
    nature: "neutral",
    warningShare: 0.35,
    opinion: "A fatura precisa ser detalhada para evitar dupla contagem.",
    action: "Categorize as compras, não apenas o pagamento da fatura.",
  },
  {
    id: "itau",
    patterns: ["Itaú","Itau"],
    category: "Cartão",
    nature: "neutral",
    warningShare: 0.35,
    opinion: "Pagamento bancário genérico dificulta o diagnóstico.",
    action: "Identifique se é fatura, tarifa ou transferência.",
  },
  {
    id: "bradesco",
    patterns: ["Bradesco"],
    category: "Cartão",
    nature: "neutral",
    warningShare: 0.35,
    opinion: "Movimentação bancária sem categoria reduz a precisão.",
    action: "Detalhe a origem do gasto.",
  },
  {
    id: "santander",
    patterns: ["Santander"],
    category: "Cartão",
    nature: "neutral",
    warningShare: 0.35,
    opinion: "Fatura alta pode esconder assinaturas e parcelas.",
    action: "Revise compras recorrentes e parceladas.",
  },
  {
    id: "picpay",
    patterns: ["PicPay"],
    category: "Carteira digital",
    nature: "neutral",
    warningShare: 0.2,
    opinion: "Transferências por carteira precisam de descrição.",
    action: "Evite contar transferência entre suas contas como gasto.",
  },
  {
    id: "paypal",
    patterns: ["PayPal"],
    category: "Carteira digital",
    nature: "neutral",
    warningShare: 0.15,
    opinion: "PayPal pode esconder o fornecedor real.",
    action: "Registre o estabelecimento final para melhorar os alertas.",
  },
  {
    id: "claro",
    patterns: ["Claro"],
    category: "Telefonia",
    nature: "essential",
    warningShare: 0.035,
    opinion: "Telefonia está acima da referência.",
    action: "Negocie o plano e remova serviços adicionais.",
  },
  {
    id: "vivo",
    patterns: ["Vivo"],
    category: "Telefonia",
    nature: "essential",
    warningShare: 0.035,
    opinion: "O plano da Vivo merece revisão.",
    action: "Compare franquia usada com a contratada.",
  },
  {
    id: "tim",
    patterns: ["TIM"],
    category: "Telefonia",
    nature: "essential",
    warningShare: 0.035,
    opinion: "Telefonia está consumindo mais que o esperado.",
    action: "Migre para um plano compatível com o uso real.",
  },
  {
    id: "oi",
    patterns: ["Oi Fibra","Oi"],
    category: "Internet",
    nature: "essential",
    warningShare: 0.04,
    opinion: "Internet está acima da faixa típica.",
    action: "Negocie fidelidade somente com desconto claro.",
  },
  {
    id: "neoenergia",
    patterns: ["Neoenergia","Coelba"],
    category: "Energia",
    nature: "essential",
    warningShare: 0.08,
    opinion: "Energia subiu e merece investigação.",
    action: "Compare consumo em kWh, não apenas o valor da conta.",
  },
  {
    id: "embasa",
    patterns: ["Embasa"],
    category: "Água",
    nature: "essential",
    warningShare: 0.035,
    opinion: "A conta de água está elevada.",
    action: "Verifique vazamentos e variação de consumo.",
  },
  {
    id: "aluguel",
    patterns: ["Aluguel","Imobiliária","Imobiliaria"],
    category: "Moradia",
    nature: "essential",
    warningShare: 0.32,
    opinion: "Moradia está acima de 32% da renda.",
    action: "Evite assumir novas parcelas e revise custos fixos.",
  },
  {
    id: "condominio",
    patterns: ["Condomínio","Condominio"],
    category: "Moradia",
    nature: "essential",
    warningShare: 0.1,
    opinion: "Condomínio está pressionando o orçamento.",
    action: "Inclua taxas extras na previsão anual.",
  },
  {
    id: "faculdade",
    patterns: ["Faculdade","Universidade","Curso"],
    category: "Educação",
    nature: "investment",
    warningShare: 0.15,
    opinion: "Educação tem valor, mas precisa caber no fluxo.",
    action: "Defina o retorno esperado e evite atrasos caros.",
  },
  {
    id: "udemy",
    patterns: ["Udemy"],
    category: "Educação",
    nature: "investment",
    warningShare: 0.025,
    opinion: "Cursos comprados e não concluídos viram desperdício.",
    action: "Conclua um curso antes de comprar outro.",
  },
  {
    id: "alura",
    patterns: ["Alura"],
    category: "Educação",
    nature: "investment",
    warningShare: 0.04,
    opinion: "A assinatura de estudos precisa de uso recorrente.",
    action: "Defina uma meta semanal de estudo.",
  },
  {
    id: "openai",
    patterns: ["OpenAI","ChatGPT"],
    category: "Software",
    nature: "mixed",
    warningShare: 0.03,
    opinion: "Ferramentas de IA devem gerar economia ou renda.",
    action: "Meça horas poupadas antes de renovar.",
  },
  {
    id: "google one",
    patterns: ["Google One"],
    category: "Software",
    nature: "mixed",
    warningShare: 0.025,
    opinion: "Armazenamento e IA precisam justificar o plano.",
    action: "Revise espaço usado e benefícios ativos.",
  },
  {
    id: "adobe",
    patterns: ["Adobe"],
    category: "Software",
    nature: "mixed",
    warningShare: 0.04,
    opinion: "Software profissional está caro para uso ocasional.",
    action: "Considere plano menor ou alternativa quando possível.",
  },
  {
    id: "canva",
    patterns: ["Canva"],
    category: "Software",
    nature: "mixed",
    warningShare: 0.025,
    opinion: "Canva Pro precisa entregar valor recorrente.",
    action: "Cancele se o uso for esporádico.",
  },
  {
    id: "lotérica",
    patterns: ["Loteria","Loterica","Betano","Bet365","Pixbet"],
    category: "Apostas",
    nature: "high-risk",
    warningShare: 0.005,
    opinion: "Apostas não são investimento e estão consumindo dinheiro.",
    action: "Interrompa aportes, defina bloqueios e nunca tente recuperar perdas.",
  },
  {
    id: "bet",
    patterns: ["Betano","Bet365","Sportingbet","KTO"],
    category: "Apostas",
    nature: "high-risk",
    warningShare: 0.005,
    opinion: "Esse gasto tem alto risco de perda e nenhum retorno previsível.",
    action: "Pare agora e redirecione o valor para uma meta concreta.",
  },
  {
    id: "cigarro",
    patterns: ["Tabacaria","Cigarro","Vape"],
    category: "Tabaco",
    nature: "high-risk",
    warningShare: 0.015,
    opinion: "Além do custo financeiro, esse gasto aumenta riscos de saúde.",
    action: "Calcule o custo anual e procure apoio para reduzir.",
  },
  {
    id: "juros",
    patterns: ["Juros","Multa","Encargos"],
    category: "Encargos",
    nature: "waste",
    warningShare: 0.001,
    opinion: "Juros e multas são dinheiro perdido.",
    action: "Ative lembretes e priorize quitar a dívida mais cara.",
  },
  {
    id: "tarifa",
    patterns: ["Tarifa bancária","Anuidade"],
    category: "Tarifas",
    nature: "waste",
    warningShare: 0.005,
    opinion: "Tarifas recorrentes podem ser evitáveis.",
    action: "Negocie isenção ou compare contas sem tarifa.",
  },
  {
    id: "emprestimo",
    patterns: ["Empréstimo","Emprestimo","Financiamento"],
    category: "Dívidas",
    nature: "debt",
    warningShare: 0.2,
    opinion: "Dívidas estão limitando sua capacidade de poupar.",
    action: "Priorize a maior taxa e evite novas parcelas.",
  },
  {
    id: "consorcio",
    patterns: ["Consórcio","Consorcio"],
    category: "Objetivos",
    nature: "mixed",
    warningShare: 0.15,
    opinion: "Consórcio exige atenção a taxas e prazo incerto.",
    action: "Compare custo total com poupança programada e financiamento.",
  },
  {
    id: "seguro",
    patterns: ["Seguro"],
    category: "Proteção",
    nature: "essential",
    warningShare: 0.08,
    opinion: "Seguro deve proteger um risco relevante sem duplicidade.",
    action: "Revise cobertura, franquia e itens já cobertos.",
  },
  {
    id: "investimento",
    patterns: ["Tesouro","CDB","LCI","LCA","Investimento"],
    category: "Investimentos",
    nature: "investment",
    warningShare: 0.25,
    opinion: "Aporte é positivo se o caixa e a reserva estiverem saudáveis.",
    action: "Mantenha diversificação, liquidez e alinhamento ao prazo.",
  },
  {
    id: "cripto",
    patterns: ["Bitcoin","Ethereum","Binance","Cripto"],
    category: "Criptoativos",
    nature: "high-risk",
    warningShare: 0.05,
    opinion: "Cripto está acima da parcela de alto risco sugerida.",
    action: "Não use reserva nem dinheiro de contas próximas.",
  },
  {
    id: "academia games",
    patterns: ["Game Pass","PlayStation Plus","Nintendo Online"],
    category: "Assinaturas de jogos",
    nature: "discretionary",
    warningShare: 0.015,
    opinion: "Assinaturas de jogos acumuladas merecem revisão.",
    action: "Mantenha somente a plataforma usada no mês.",
  },
  {
    id: "delivery mercado",
    patterns: ["Daki","Oxxo","Justo"],
    category: "Conveniência",
    nature: "discretionary",
    warningShare: 0.05,
    opinion: "Compras por conveniência têm preço maior.",
    action: "Planeje reposições para evitar taxas e sobrepreço.",
  },
  {
    id: "roupas",
    patterns: ["Renner","Riachuelo","C&A","Zara"],
    category: "Vestuário",
    nature: "discretionary",
    warningShare: 0.05,
    opinion: "Vestuário está acima da faixa do mês.",
    action: "Faça inventário do armário antes de comprar.",
  },
  {
    id: "beleza",
    patterns: ["Natura","O Boticário","Sephora"],
    category: "Cuidados pessoais",
    nature: "discretionary",
    warningShare: 0.04,
    opinion: "Cuidados pessoais estão consumindo uma fatia alta.",
    action: "Use o estoque atual antes de repor.",
  },
  {
    id: "moveis",
    patterns: ["Tok&Stok","MadeiraMadeira","Mobly"],
    category: "Casa",
    nature: "mixed",
    warningShare: 0.1,
    opinion: "Móveis têm impacto grande e devem ser planejados.",
    action: "Crie uma meta específica e evite parcelamento longo.",
  },
  {
    id: "material",
    patterns: ["Leroy Merlin","Telhanorte","Ferreira Costa"],
    category: "Casa",
    nature: "mixed",
    warningShare: 0.1,
    opinion: "Reformas costumam ultrapassar o orçamento.",
    action: "Inclua margem de 15% e compre por etapas.",
  },
  {
    id: "presente",
    patterns: ["Presente","Gift"],
    category: "Presentes",
    nature: "discretionary",
    warningShare: 0.04,
    opinion: "Presentes estão acima do orçamento planejado.",
    action: "Defina um valor anual dividido por mês.",
  },
  {
    id: "saque",
    patterns: ["Saque"],
    category: "Dinheiro",
    nature: "neutral",
    warningShare: 0.1,
    opinion: "Saques sem detalhamento deixam gastos invisíveis.",
    action: "Registre como o dinheiro foi usado.",
  },
  {
    id: "pix",
    patterns: ["Pix enviado","Transferência"],
    category: "Transferência",
    nature: "neutral",
    warningShare: 0.2,
    opinion: "Transferência não deveria ser tratada automaticamente como despesa.",
    action: "Informe o destino real ou marque como transferência entre contas.",
  },
  {
    id: "salario",
    patterns: ["Salário","Salario","Pagamento empresa"],
    category: "Renda",
    nature: "income",
    warningShare: 1,
    opinion: "Essa é sua principal base para planejar o mês.",
    action: "Programe metas e contas logo após o recebimento.",
  },
  {
    id: "freelance",
    patterns: ["Freelance","Job","Projeto"],
    category: "Renda variável",
    nature: "income",
    warningShare: 1,
    opinion: "Renda variável não deve sustentar custos fixos sozinha.",
    action: "Use uma média conservadora e reserve meses fortes.",
  },
  {
    id: "cashback",
    patterns: ["Cashback","Estorno"],
    category: "Reembolso",
    nature: "income",
    warningShare: 1,
    opinion: "Cashback e estorno não são renda recorrente.",
    action: "Não use esses valores para assumir novas despesas.",
  },
];

export const GENERAL_FINANCIAL_GUIDANCE = {
  emergencyReserveMonths: 6,
  housingIncomeShare: 0.32,
  debtIncomeShare: 0.2,
  discretionaryIncomeShare: 0.3,
  minimumSavingsRate: 0.1,
  healthySavingsRate: 0.2,
  criticalCreditShare: 0.4,
  goalMinimumMonthlyProgress: 0.02,
  overduePriorityDays: 0,
  upcomingWarningDays: 3,
};

